### ISSUE TITLE
Catch sin sentido en la carga del excel

### ISSUE THREAD

**Issue by DanielAlba96** [Arquisoft/citizensLoader1a#13]
En ExcelLoader:
¿Para que haces un catch de file not found y dentro lo único que haces es volver a lanzarla? ¿No seria mas fácil escribir en log y terminar la ejecución en lugar de propagarla? Lo digo porque me influye a mi a la hora de hacer el main.

**Comment by duque96** [comment]
Hice que la lanzase para que así en el test pueda recogerla y comprobar que se produce la excepción cuando no se encuentra el fichero.

**Comment by DanielAlba96** [comment]
Bueno entonces puedes dejar el catch y ponerle que escriba en el log o quitarlo, porque realmente tal y como esta son lineas extra que no aportan nada. Si eso lanza un file not found lo va a lanzar independientemente del catch. Aunque lo mejor (creo) seria dejarlo y poner después ahí una llamada al log para apuntarlo. Me inventare algo para pillarla desde el main
